// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBal6CkpHA1WDwLk-rCZPc9VRXK-uvsT2M',
    appId: '1:749016956909:web:c9ecf74fcd72bc828831e4',
    messagingSenderId: '749016956909',
    projectId: 'smartcomm-6f42b',
    authDomain: 'smartcomm-6f42b.firebaseapp.com',
    storageBucket: 'smartcomm-6f42b.firebasestorage.app',
    measurementId: 'G-VK7YGQJBRJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQkCbve4yDFg01SNQulw_RwLtxK3LUpT0',
    appId: '1:749016956909:android:4d37f215a8fbee828831e4',
    messagingSenderId: '749016956909',
    projectId: 'smartcomm-6f42b',
    storageBucket: 'smartcomm-6f42b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMJi4_w-shxRfKJcqiDAd61g5w1CmxS48',
    appId: '1:749016956909:ios:c7860b788252f2068831e4',
    messagingSenderId: '749016956909',
    projectId: 'smartcomm-6f42b',
    storageBucket: 'smartcomm-6f42b.firebasestorage.app',
    iosBundleId: 'com.niagaraautomations.oroDevelopment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMJi4_w-shxRfKJcqiDAd61g5w1CmxS48',
    appId: '1:749016956909:ios:a49edfcef198fddf8831e4',
    messagingSenderId: '749016956909',
    projectId: 'smartcomm-6f42b',
    storageBucket: 'smartcomm-6f42b.firebasestorage.app',
    iosBundleId: 'com.niagaraautomations.oroDripIrrigation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBal6CkpHA1WDwLk-rCZPc9VRXK-uvsT2M',
    appId: '1:749016956909:web:8e465822ac04c06c8831e4',
    messagingSenderId: '749016956909',
    projectId: 'smartcomm-6f42b',
    authDomain: 'smartcomm-6f42b.firebaseapp.com',
    storageBucket: 'smartcomm-6f42b.firebasestorage.app',
    measurementId: 'G-T7PJCESKL8',
  );

}